#ifndef MANTARAY_MANTA_BUILD_CONF_H
#define MANTARAY_MANTA_BUILD_CONF_H

#define ENABLE_PATH_RECORDING (false)
#define INCLUDE_OPENCL_IMPL (false)
#define ENABLE_DETAILED_STATISTICS (true)

#endif /* MANTARAY_MANTA_BUILD_CONF_H */
