#ifndef MANTA_BUILD_CONF_H
#define MANTA_BUILD_CONF_H

#define ENABLE_PATH_RECORDING (false)
#define INCLUDE_OPENCL_IMPL (false)
#define ENABLE_DETAILED_STATISTICS (true)

#endif /* MANTA_BUILD_CONF_H */
